LB:
  ports:
  - ${lbport}:8080
  - 5083:9990
  tty: true
  image: rancher/load-balancer-service
  links:
  - wfsrv:wfsrv
  stdin_open: true
wfsrv:
  environment:
    APPLICATION_NAME: ${application_name}
    ARTIFACT_URL: ${artifact_url}
    DATASOURCE_NAME: ${datasource_name}
    DATABASE_HOST: ${database_host}
    DATABASE_USERNAME: ${database_username}
    DATABASE_PASSWORD: ${database_password}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: 172.31.12.94:5000/jboss-wildfly:1.2
  stdin_open: true
